// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTTNgoaiNgu.Data;

#nullable disable

namespace QuanLyTTNgoaiNgu.Migrations
{
    [DbContext(typeof(QuanLyTTNgoaiNguContext))]
    [Migration("20251125072715_AddChoXacNhanToHocPhi")]
    partial class AddChoXacNhanToHocPhi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DANGKYMOIQUANTRIVIEN", b =>
                {
                    b.Property<int>("DangKyMoiMaDangKy")
                        .HasColumnType("int");

                    b.Property<int>("QUANTRIVIENsMaQuanTriVien")
                        .HasColumnType("int");

                    b.HasKey("DangKyMoiMaDangKy", "QUANTRIVIENsMaQuanTriVien");

                    b.HasIndex("QUANTRIVIENsMaQuanTriVien");

                    b.ToTable("DANGKYMOIQUANTRIVIEN");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.DANGKYMOI", b =>
                {
                    b.Property<int>("MaDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDangKy"));

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaQuanTriVien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaDangKy");

                    b.ToTable("DANGKYMOI");

                    b.HasData(
                        new
                        {
                            MaDangKy = 1,
                            DaDuyet = false,
                            DiaChi = "Hanoi",
                            Email = "mai@gmail.com",
                            HoTen = "Phạm Thị Mai",
                            MaQuanTriVien = 1,
                            NgaySinh = new DateTime(2003, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "123456"
                        },
                        new
                        {
                            MaDangKy = 2,
                            DaDuyet = false,
                            DiaChi = "ThaiNguyen",
                            Email = "nam@gmail.com",
                            HoTen = "Lê Văn Nam",
                            MaQuanTriVien = 1,
                            NgaySinh = new DateTime(2004, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "123654"
                        },
                        new
                        {
                            MaDangKy = 3,
                            DaDuyet = false,
                            DiaChi = "NamDinh",
                            Email = "thu@gmail.com",
                            HoTen = "Vũ Thị Thu",
                            MaQuanTriVien = 2,
                            NgaySinh = new DateTime(2005, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "321456"
                        },
                        new
                        {
                            MaDangKy = 4,
                            DaDuyet = false,
                            DiaChi = "HaiDuong",
                            Email = "long@gmail.com",
                            HoTen = "Ngô Đức Long",
                            MaQuanTriVien = 2,
                            NgaySinh = new DateTime(2003, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "456123"
                        },
                        new
                        {
                            MaDangKy = 5,
                            DaDuyet = false,
                            DiaChi = "PhuTho",
                            Email = "nhung@gmail.com",
                            HoTen = "Trần Hồng Nhung",
                            MaQuanTriVien = 3,
                            NgaySinh = new DateTime(2004, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "456321"
                        },
                        new
                        {
                            MaDangKy = 6,
                            DaDuyet = false,
                            DiaChi = "HaiPhong",
                            Email = "ly@gmail.com",
                            HoTen = "Nguyễn Thị Lý",
                            MaQuanTriVien = 1,
                            NgaySinh = new DateTime(2005, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "145236"
                        },
                        new
                        {
                            MaDangKy = 7,
                            DaDuyet = false,
                            DiaChi = "NinhBinh",
                            Email = "duongductin02@gmail.com",
                            HoTen = "Dương Đức Tin",
                            MaQuanTriVien = 3,
                            NgaySinh = new DateTime(2003, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoDienThoai = "652341"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.GIANGVIEN", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("ChuyenMon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("GIANGVIEN");

                    b.HasData(
                        new
                        {
                            MaGiangVien = 1,
                            ChuyenMon = "Tiếng Anh",
                            Email = "trung@gmail.com",
                            HoTen = "Cao Đình Trung",
                            MaTaiKhoan = 11,
                            SoDienThoai = "987654"
                        },
                        new
                        {
                            MaGiangVien = 2,
                            ChuyenMon = "Tiếng Anh",
                            Email = "diep@gmail.com",
                            HoTen = "Dương Văn Điệp",
                            MaTaiKhoan = 12,
                            SoDienThoai = "987456"
                        },
                        new
                        {
                            MaGiangVien = 3,
                            ChuyenMon = "Tiếng Trung",
                            Email = "bich@gmail.com",
                            HoTen = "Trần Thị Bích",
                            MaTaiKhoan = 13,
                            SoDienThoai = "456789"
                        },
                        new
                        {
                            MaGiangVien = 4,
                            ChuyenMon = "Tiếng Hàn",
                            Email = "van@gmail.com",
                            HoTen = "Ngô Thanh Vân",
                            MaTaiKhoan = 14,
                            SoDienThoai = "456987"
                        },
                        new
                        {
                            MaGiangVien = 5,
                            ChuyenMon = "Tiếng Nhật",
                            Email = "hiep@gmail.com",
                            HoTen = "Vũ Quang Hiệp",
                            MaTaiKhoan = 15,
                            SoDienThoai = "965874"
                        },
                        new
                        {
                            MaGiangVien = 6,
                            ChuyenMon = "Tiếng Đức",
                            Email = "tam@gmail.com",
                            HoTen = "Lê Minh Tâm",
                            MaTaiKhoan = 16,
                            SoDienThoai = "478569"
                        },
                        new
                        {
                            MaGiangVien = 7,
                            ChuyenMon = "Tiếng Trung",
                            Email = "ngoc@gmail.com",
                            HoTen = "Trần Văn Ngọc",
                            MaTaiKhoan = 17,
                            SoDienThoai = "785496"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCPHI", b =>
                {
                    b.Property<int>("MaHocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocPhi"));

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayNop")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHocPhi");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.ToTable("HOCPHI");

                    b.HasData(
                        new
                        {
                            MaHocPhi = 1,
                            MaPhieu = 1,
                            NgayNop = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            MaHocPhi = 2,
                            MaPhieu = 2,
                            NgayNop = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            MaHocPhi = 3,
                            MaPhieu = 3,
                            TrangThai = false
                        },
                        new
                        {
                            MaHocPhi = 4,
                            MaPhieu = 4,
                            NgayNop = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            MaHocPhi = 5,
                            MaPhieu = 5,
                            TrangThai = false
                        },
                        new
                        {
                            MaHocPhi = 6,
                            MaPhieu = 6,
                            NgayNop = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        },
                        new
                        {
                            MaHocPhi = 7,
                            MaPhieu = 7,
                            NgayNop = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCVIEN", b =>
                {
                    b.Property<int>("MaHocVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocVien"));

                    b.Property<int>("MaDangKy")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaDangKy")
                        .IsUnique();

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("HOCVIEN");

                    b.HasData(
                        new
                        {
                            MaHocVien = 1,
                            MaDangKy = 1,
                            MaTaiKhoan = 21
                        },
                        new
                        {
                            MaHocVien = 2,
                            MaDangKy = 2,
                            MaTaiKhoan = 22
                        },
                        new
                        {
                            MaHocVien = 3,
                            MaDangKy = 3,
                            MaTaiKhoan = 23
                        },
                        new
                        {
                            MaHocVien = 4,
                            MaDangKy = 4,
                            MaTaiKhoan = 24
                        },
                        new
                        {
                            MaHocVien = 5,
                            MaDangKy = 5,
                            MaTaiKhoan = 25
                        },
                        new
                        {
                            MaHocVien = 6,
                            MaDangKy = 6,
                            MaTaiKhoan = 26
                        },
                        new
                        {
                            MaHocVien = 7,
                            MaDangKy = 7,
                            MaTaiKhoan = 27
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KETQUAHOCTAP", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.ToTable("KETQUAHOCTAP");

                    b.HasData(
                        new
                        {
                            MaKetQua = 1,
                            Diem = 8.5,
                            MaPhieu = 1
                        },
                        new
                        {
                            MaKetQua = 2,
                            Diem = 4.0,
                            MaPhieu = 2
                        },
                        new
                        {
                            MaKetQua = 3,
                            Diem = 7.5,
                            MaPhieu = 3
                        },
                        new
                        {
                            MaKetQua = 4,
                            Diem = 5.0,
                            MaPhieu = 4
                        },
                        new
                        {
                            MaKetQua = 5,
                            Diem = 6.5,
                            MaPhieu = 5
                        },
                        new
                        {
                            MaKetQua = 6,
                            Diem = 8.0,
                            MaPhieu = 6
                        },
                        new
                        {
                            MaKetQua = 7,
                            Diem = 9.0,
                            MaPhieu = 7
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KHOAHOC", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MucHocPhi")
                        .HasColumnType("float");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KHOAHOC");

                    b.HasData(
                        new
                        {
                            MaKhoaHoc = 1,
                            MoTa = "Khóa học tiếng Anh cơ bản dành cho người mới bắt đầu.",
                            MucHocPhi = 2000000.0,
                            TenKhoaHoc = "Tiếng Anh Cơ Bản"
                        },
                        new
                        {
                            MaKhoaHoc = 2,
                            MoTa = "Khóa học tiếng Anh nâng cao cho người đã có kiến thức cơ bản.",
                            MucHocPhi = 3000000.0,
                            TenKhoaHoc = "Tiếng Anh Nâng Cao"
                        },
                        new
                        {
                            MaKhoaHoc = 3,
                            MoTa = "Khóa học tiếng Trung cơ bản dành cho người mới bắt đầu.",
                            MucHocPhi = 2500000.0,
                            TenKhoaHoc = "Tiếng Trung Cơ Bản"
                        },
                        new
                        {
                            MaKhoaHoc = 4,
                            MoTa = "Khóa học tiếng Hàn cơ bản dành cho người mới bắt đầu.",
                            MucHocPhi = 2800000.0,
                            TenKhoaHoc = "Tiếng Hàn Cơ Bản"
                        },
                        new
                        {
                            MaKhoaHoc = 5,
                            MoTa = "Khóa học tiếng Nhật cơ bản dành cho người mới bắt đầu.",
                            MucHocPhi = 2700000.0,
                            TenKhoaHoc = "Tiếng Nhật Cơ Bản"
                        },
                        new
                        {
                            MaKhoaHoc = 6,
                            MoTa = "Khóa học tiếng Đức cơ bản dành cho người mới bắt đầu.",
                            MucHocPhi = 2600000.0,
                            TenKhoaHoc = "Tiếng Đức Cơ Bản"
                        },
                        new
                        {
                            MaKhoaHoc = 7,
                            MoTa = "Khóa học tiếng Trung nâng cao cho người đã có kiến thức cơ bản.",
                            MucHocPhi = 3500000.0,
                            TenKhoaHoc = "Tiếng Trung Nâng Cao"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.LOPHOC", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SLHocVienToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("LOPHOC");

                    b.HasData(
                        new
                        {
                            MaLopHoc = 1,
                            MaGiangVien = 1,
                            MaKhoaHoc = 1,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SLHocVienToiDa = 50,
                            TenLopHoc = "Lớp Tiếng Anh Cơ Bản 1"
                        },
                        new
                        {
                            MaLopHoc = 2,
                            MaGiangVien = 2,
                            MaKhoaHoc = 2,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SLHocVienToiDa = 50,
                            TenLopHoc = "Lớp Tiếng Anh Nâng Cao 1"
                        },
                        new
                        {
                            MaLopHoc = 3,
                            MaGiangVien = 3,
                            MaKhoaHoc = 3,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SLHocVienToiDa = 50,
                            TenLopHoc = "Lớp Tiếng Trung Cơ Bản 1"
                        },
                        new
                        {
                            MaLopHoc = 4,
                            MaGiangVien = 4,
                            MaKhoaHoc = 4,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SLHocVienToiDa = 50,
                            TenLopHoc = "Lớp Tiếng Hàn Cơ Bản 1"
                        },
                        new
                        {
                            MaLopHoc = 5,
                            MaGiangVien = 5,
                            MaKhoaHoc = 5,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SLHocVienToiDa = 50,
                            TenLopHoc = "Lớp Tiếng Nhật Cơ Bản 1"
                        },
                        new
                        {
                            MaLopHoc = 6,
                            MaGiangVien = 6,
                            MaKhoaHoc = 6,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SLHocVienToiDa = 50,
                            TenLopHoc = "Lớp Tiếng Đức Cơ Bản 1"
                        },
                        new
                        {
                            MaLopHoc = 7,
                            MaGiangVien = 7,
                            MaKhoaHoc = 7,
                            NgayBatDau = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SLHocVienToiDa = 50,
                            TenLopHoc = "Lớp Tiếng Trung Nâng Cao 1"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"));

                    b.Property<int>("MaHocVien")
                        .HasColumnType("int");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDangKy")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaHocVien");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("PHIEUDANGKY");

                    b.HasData(
                        new
                        {
                            MaPhieu = 1,
                            MaHocVien = 1,
                            MaLopHoc = 1,
                            NgayDangKy = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaPhieu = 2,
                            MaHocVien = 2,
                            MaLopHoc = 2,
                            NgayDangKy = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaPhieu = 3,
                            MaHocVien = 3,
                            MaLopHoc = 3,
                            NgayDangKy = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaPhieu = 4,
                            MaHocVien = 4,
                            MaLopHoc = 4,
                            NgayDangKy = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaPhieu = 5,
                            MaHocVien = 5,
                            MaLopHoc = 5,
                            NgayDangKy = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaPhieu = 6,
                            MaHocVien = 6,
                            MaLopHoc = 6,
                            NgayDangKy = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaPhieu = 7,
                            MaHocVien = 7,
                            MaLopHoc = 7,
                            NgayDangKy = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.QUANTRIVIEN", b =>
                {
                    b.Property<int>("MaQuanTriVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuanTriVien"));

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TenQuanTriVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuanTriVien");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("QUANTRIVIEN");

                    b.HasData(
                        new
                        {
                            MaQuanTriVien = 1,
                            MaTaiKhoan = 1,
                            TenQuanTriVien = "Đào Văn Quân"
                        },
                        new
                        {
                            MaQuanTriVien = 2,
                            MaTaiKhoan = 2,
                            TenQuanTriVien = "Vũ Thanh Ngọc"
                        },
                        new
                        {
                            MaQuanTriVien = 3,
                            MaTaiKhoan = 3,
                            TenQuanTriVien = "Dương Đức Tín"
                        },
                        new
                        {
                            MaQuanTriVien = 4,
                            MaTaiKhoan = 4,
                            TenQuanTriVien = "Nguyễn Viết Trường"
                        },
                        new
                        {
                            MaQuanTriVien = 5,
                            MaTaiKhoan = 5,
                            TenQuanTriVien = "Nguyễn Anh Tuấn"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.TAIKHOAN", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TAIKHOAN");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            MatKhau = "admin123",
                            TenDangNhap = "admin1",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 2,
                            MatKhau = "admin123",
                            TenDangNhap = "admin2",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 3,
                            MatKhau = "admin123",
                            TenDangNhap = "admin3",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 4,
                            MatKhau = "admin123",
                            TenDangNhap = "admin4",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 5,
                            MatKhau = "admin123",
                            TenDangNhap = "admin5",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = 11,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien1",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 12,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien2",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 13,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien3",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 14,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien4",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 15,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien5",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 16,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien5",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 17,
                            MatKhau = "123456",
                            TenDangNhap = "giaovien6",
                            VaiTro = "GiangVien"
                        },
                        new
                        {
                            MaTaiKhoan = 21,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien1",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 22,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien2",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 23,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien3",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 24,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien4",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 25,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien5",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 26,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien6",
                            VaiTro = "HocVien"
                        },
                        new
                        {
                            MaTaiKhoan = 27,
                            MatKhau = "123456",
                            TenDangNhap = "hocvien7",
                            VaiTro = "HocVien"
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.THOIKHOABIEU", b =>
                {
                    b.Property<int>("MaLichHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichHoc"));

                    b.Property<string>("CaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayHoc")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichHoc");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("THOIKHOABIEU");

                    b.HasData(
                        new
                        {
                            MaLichHoc = 11,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 1,
                            NgayHoc = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 12,
                            CaHoc = "3-5 (9h - 11h)",
                            MaLopHoc = 1,
                            NgayHoc = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 13,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 1,
                            NgayHoc = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 21,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 2,
                            NgayHoc = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 22,
                            CaHoc = "5-7 (13h - 15h)",
                            MaLopHoc = 2,
                            NgayHoc = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 23,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 2,
                            NgayHoc = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 31,
                            CaHoc = "3-5 (9h - 11h)",
                            MaLopHoc = 3,
                            NgayHoc = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 32,
                            CaHoc = "7-9 (15h - 17h)",
                            MaLopHoc = 3,
                            NgayHoc = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 33,
                            CaHoc = "3-5 (9h - 11h)",
                            MaLopHoc = 3,
                            NgayHoc = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 41,
                            CaHoc = "3-5 (9h - 11h)",
                            MaLopHoc = 4,
                            NgayHoc = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 42,
                            CaHoc = "5-7 (13h - 15h)",
                            MaLopHoc = 4,
                            NgayHoc = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 43,
                            CaHoc = "5-7 (13h - 15h)",
                            MaLopHoc = 4,
                            NgayHoc = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 51,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 5,
                            NgayHoc = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 52,
                            CaHoc = "5-7 (13h - 15h)",
                            MaLopHoc = 5,
                            NgayHoc = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 53,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 5,
                            NgayHoc = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 61,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 6,
                            NgayHoc = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 62,
                            CaHoc = "5-7 (13h - 15h)",
                            MaLopHoc = 6,
                            NgayHoc = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 63,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 6,
                            NgayHoc = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 71,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 7,
                            NgayHoc = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 72,
                            CaHoc = "7-9 (15h - 17h)",
                            MaLopHoc = 7,
                            NgayHoc = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLichHoc = 73,
                            CaHoc = "1-3 (7h - 9h)",
                            MaLopHoc = 7,
                            NgayHoc = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.THONGBAO", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThongBao")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TAIKHOANMaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaTaiKhoan");

                    b.HasIndex("TAIKHOANMaTaiKhoan");

                    b.ToTable("THONGBAO");

                    b.HasData(
                        new
                        {
                            MaThongBao = 1,
                            MaTaiKhoan = 1,
                            NgayThongBao = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Lịch học sẽ bắt đầu từ ngày 1 tháng 9 năm 2025.",
                            TieuDe = "Thông báo lịch học"
                        },
                        new
                        {
                            MaThongBao = 2,
                            MaTaiKhoan = 2,
                            NgayThongBao = new DateTime(2025, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Học phí cho khóa học tiếng Anh cơ bản là 2.000.000 VNĐ.",
                            TieuDe = "Thông báo học phí"
                        },
                        new
                        {
                            MaThongBao = 3,
                            MaTaiKhoan = 3,
                            NgayThongBao = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDung = "Các bạn học viên vui lòng đăng ký lớp học trước ngày 30 tháng 8 năm 2025.",
                            TieuDe = "Thông báo đăng ký lớp học"
                        });
                });

            modelBuilder.Entity("DANGKYMOIQUANTRIVIEN", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.DANGKYMOI", null)
                        .WithMany()
                        .HasForeignKey("DangKyMoiMaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.QUANTRIVIEN", null)
                        .WithMany()
                        .HasForeignKey("QUANTRIVIENsMaQuanTriVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.GIANGVIEN", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", "TAIKHOAN")
                        .WithMany("GIANGVIENs")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TAIKHOAN");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCPHI", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", "PHIEUDANGKY")
                        .WithOne("HOCPHI")
                        .HasForeignKey("QuanLyTTNgoaiNgu.Models.HOCPHI", "MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PHIEUDANGKY");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCVIEN", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.DANGKYMOI", "DANGKYMOI")
                        .WithOne("HOCVIEN")
                        .HasForeignKey("QuanLyTTNgoaiNgu.Models.HOCVIEN", "MaDangKy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", "TAIKHOAN")
                        .WithMany("HOCVIENs")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DANGKYMOI");

                    b.Navigation("TAIKHOAN");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KETQUAHOCTAP", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", "PHIEUDANGKY")
                        .WithOne("KETQUAHOCTAP")
                        .HasForeignKey("QuanLyTTNgoaiNgu.Models.KETQUAHOCTAP", "MaPhieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PHIEUDANGKY");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.LOPHOC", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.GIANGVIEN", "GIANGVIEN")
                        .WithMany("LOPHOCs")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.KHOAHOC", "KHOAHOC")
                        .WithMany("LOPHOCs")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GIANGVIEN");

                    b.Navigation("KHOAHOC");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.HOCVIEN", "HOCVIEN")
                        .WithMany("PHIEUDANGKies")
                        .HasForeignKey("MaHocVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.LOPHOC", "LOPHOC")
                        .WithMany("PHIEUDANGKies")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HOCVIEN");

                    b.Navigation("LOPHOC");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.QUANTRIVIEN", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", "TaiKhoan")
                        .WithMany("QUANTRIVIENs")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.THOIKHOABIEU", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.LOPHOC", "LOPHOC")
                        .WithMany("THOIKHOABIEUs")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LOPHOC");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.THONGBAO", b =>
                {
                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTTNgoaiNgu.Models.TAIKHOAN", null)
                        .WithMany("THONGBAOs")
                        .HasForeignKey("TAIKHOANMaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.DANGKYMOI", b =>
                {
                    b.Navigation("HOCVIEN");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.GIANGVIEN", b =>
                {
                    b.Navigation("LOPHOCs");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.HOCVIEN", b =>
                {
                    b.Navigation("PHIEUDANGKies");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.KHOAHOC", b =>
                {
                    b.Navigation("LOPHOCs");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.LOPHOC", b =>
                {
                    b.Navigation("PHIEUDANGKies");

                    b.Navigation("THOIKHOABIEUs");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.PHIEUDANGKY", b =>
                {
                    b.Navigation("HOCPHI");

                    b.Navigation("KETQUAHOCTAP");
                });

            modelBuilder.Entity("QuanLyTTNgoaiNgu.Models.TAIKHOAN", b =>
                {
                    b.Navigation("GIANGVIENs");

                    b.Navigation("HOCVIENs");

                    b.Navigation("QUANTRIVIENs");

                    b.Navigation("THONGBAOs");
                });
#pragma warning restore 612, 618
        }
    }
}
